# 配置微服务
server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    # 94.191.18.238
    url: jdbc:mysql://94.191.18.238:3306/heima
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ROOT123456
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
# 配置注册中心
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl